/**
 * Datos de geomorfositios de Costa Rica.
 * Fuente: inventario CSV (Geomorfositios.csv) — 65 registros de parques nacionales.
 * Cada objeto conserva los campos originales del inventario:
 * id, category (normalizada para agrupar en el sitio), name, region, lat, lng,
 * elevation_m, areaProtegida, provincia, canton, distrito, proceso (texto original
 * del inventario), caracteristica, clasificacion, valorCientifico, valorAnadido, summary
 * (generado a partir de los campos anteriores; no hay fotografías en la fuente).
 */
const SITES = [
  {
    id: 'pvavol001',
    category: 'volcanico',
    name: 'Cráter Principal',
    region: 'Toro Amarillo, Sarchí, Alajuela',
    lat: 10.1958333333333,
    lng: -84.2419444444444,
    elevation_m: 2268,
    areaProtegida: 'Parque Nacional Volcán Poás',
    provincia: 'Alajuela',
    canton: 'Sarchí',
    distrito: 'Toro Amarillo',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.94,
    valorAnadido: 0.94,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Poás, en el distrito de Toro Amarillo, cantón de Sarchí, provincia de Alajuela, a 2268 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.94, valor añadido 0.94). Carácter: Natural.'
  },
  {
    id: 'pvavol002',
    category: 'volcanico',
    name: 'Cono Botos',
    region: 'Sabana Redonda, Poás, Alajuela',
    lat: 10.1866666666667,
    lng: -84.2266666666667,
    elevation_m: 2708,
    areaProtegida: 'Parque Nacional Volcán Poás',
    provincia: 'Alajuela',
    canton: 'Poás',
    distrito: 'Sabana Redonda',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.86,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Poás, en el distrito de Sabana Redonda, cantón de Poás, provincia de Alajuela, a 2708 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.86). Carácter: Natural.'
  },
  {
    id: 'pvavol003',
    category: 'volcanico',
    name: 'Cono Von Fratzius',
    region: 'Toro Amarillo, Sarchí, Alajuela',
    lat: 10.2133333333333,
    lng: -84.2302777777778,
    elevation_m: 2639,
    areaProtegida: 'Parque Nacional Volcán Poás',
    provincia: 'Alajuela',
    canton: 'Sarchí',
    distrito: 'Toro Amarillo',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.85,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Poás, en el distrito de Toro Amarillo, cantón de Sarchí, provincia de Alajuela, a 2639 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.85). Carácter: Natural.'
  },
  {
    id: 'pvavol004',
    category: 'volcanico',
    name: 'Volcán Congo',
    region: 'Río Cuarto, Río Cuarto, Alajuela',
    lat: 10.2616666666667,
    lng: -84.2275,
    elevation_m: 2014,
    areaProtegida: 'Parque Nacional Volcán Poás',
    provincia: 'Alajuela',
    canton: 'Río Cuarto',
    distrito: 'Río Cuarto',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.5,
    valorAnadido: 0.3,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Poás, en el distrito de Río Cuarto, cantón de Río Cuarto, provincia de Alajuela, a 2014 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.50, valor añadido 0.30). Carácter: Natural.'
  },
  {
    id: 'pvavol005',
    category: 'volcanico',
    name: 'Relicto Calderico',
    region: 'Toro Amarillo, Sarchí, Alajuela',
    lat: 10.1872222222222,
    lng: -84.2388888888889,
    elevation_m: 2564,
    areaProtegida: 'Parque Nacional Volcán Poás',
    provincia: 'Alajuela',
    canton: 'Sarchí',
    distrito: 'Toro Amarillo',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.19,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Poás, en el distrito de Toro Amarillo, cantón de Sarchí, provincia de Alajuela, a 2564 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.19, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'iravol001',
    category: 'volcanico',
    name: 'Cráter Principal',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.9825,
    lng: -83.8497222222222,
    elevation_m: 3174,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.94,
    valorAnadido: 0.92,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3174 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.94, valor añadido 0.92). Carácter: Natural.'
  },
  {
    id: 'iravol002',
    category: 'volcanico',
    name: 'Cráter Diego de la Haya',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.98138888888889,
    lng: -83.8458333333333,
    elevation_m: 3275,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.9,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3275 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.90). Carácter: Natural.'
  },
  {
    id: 'iravol003',
    category: 'volcanico',
    name: 'Cráter Playa Hermosa',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.97777777777778,
    lng: -83.8491666666667,
    elevation_m: 3312,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.75,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3312 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.75). Carácter: Natural.'
  },
  {
    id: 'iravol004',
    category: 'volcanico',
    name: 'Domo',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.97944444444444,
    lng: -83.8427777777778,
    elevation_m: 3384,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.31,
    valorAnadido: 0.2,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3384 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.31, valor añadido 0.20). Carácter: Natural.'
  },
  {
    id: 'iravol005',
    category: 'volcanico',
    name: 'Cueva Los Minerales',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.98666666666667,
    lng: -83.8541666666667,
    elevation_m: 2905,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 2905 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'iravol006',
    category: 'volcanico',
    name: 'Cueva Los Mucolitos',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.98722222222222,
    lng: -83.8544444444444,
    elevation_m: 2890,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 2890 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'iravol007',
    category: 'volcanico',
    name: 'Cerro Retes',
    region: 'Cascajal, Vázquez de Coronado, San José',
    lat: 9.97166666666667,
    lng: -83.8716666666667,
    elevation_m: 3180,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'San José',
    canton: 'Vázquez de Coronado',
    distrito: 'Cascajal',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.38,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Cascajal, cantón de Vázquez de Coronado, provincia de San José, a 3180 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.38, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'iravol008',
    category: 'volcanico',
    name: 'Cerro Cabeza de Vaca',
    region: 'Llano Grande, Cartago, Cartago',
    lat: 9.96944444444444,
    lng: -83.8872222222222,
    elevation_m: 3059,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Cartago',
    distrito: 'Llano Grande',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.63,
    valorAnadido: 0.62,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Llano Grande, cantón de Cartago, provincia de Cartago, a 3059 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.63, valor añadido 0.62). Carácter: Natural.'
  },
  {
    id: 'iravol009',
    category: 'volcanico',
    name: 'Laguna Reventado',
    region: 'Tierra Blanca, Cartago, Cartago',
    lat: 9.96777777777778,
    lng: -83.8694444444444,
    elevation_m: 2982,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Cartago',
    distrito: 'Tierra Blanca',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.56,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Tierra Blanca, cantón de Cartago, provincia de Cartago, a 2982 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.56, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'iravol010',
    category: 'volcanico',
    name: 'Cráter Valle Lunar',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.98111111111111,
    lng: -83.8372222222222,
    elevation_m: 3272,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.5,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3272 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.50, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'iravol011',
    category: 'volcanico',
    name: 'Cerro Sapper',
    region: 'Santa Rosa, Oreamuno, Cartago',
    lat: 9.97666666666667,
    lng: -83.8533333333333,
    elevation_m: 3432,
    areaProtegida: 'Parque Nacional Volcán Irazú',
    provincia: 'Cartago',
    canton: 'Oreamuno',
    distrito: 'Santa Rosa',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.81,
    valorAnadido: 0.79,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Volcán Irazú, en el distrito de Santa Rosa, cantón de Oreamuno, provincia de Cartago, a 3432 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.81, valor añadido 0.79). Carácter: Natural.'
  },
  {
    id: 'chigla001',
    category: 'glaciar',
    name: 'Valle Talari',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.45555555555556,
    lng: -83.5047222222222,
    elevation_m: 3320,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glacial y fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.5,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso glacial y fluvial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3320 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.50, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'chigla002',
    category: 'glaciar',
    name: 'Valle de los Conejos',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.46555555555556,
    lng: -83.4941666666667,
    elevation_m: 3500,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glacial y fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.69,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso glacial y fluvial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3500 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.69, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'chigla003',
    category: 'glaciar',
    name: 'Valle de los Lagos',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.48138888888889,
    lng: -83.4938888888889,
    elevation_m: 3520,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glacial y fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.81,
    valorAnadido: 0.79,
    summary: 'Geomorfositio de proceso glacial y fluvial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3520 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.81, valor añadido 0.79). Carácter: Natural.'
  },
  {
    id: 'chigla004',
    category: 'glaciar',
    name: 'Cerro Chirripó',
    region: 'Valle La Estrella, Limón, Limón',
    lat: 9.48444444444444,
    lng: -83.4886111111111,
    elevation_m: 3820,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Limón',
    canton: 'Limón',
    distrito: 'Valle La Estrella',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.86,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Valle La Estrella, cantón de Limón, provincia de Limón, a 3820 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.86). Carácter: Natural.'
  },
  {
    id: 'chigla005',
    category: 'glaciar',
    name: 'Valle de las Morrenas',
    region: 'Valle La Estrella, Limón, Limón',
    lat: 9.49111111111111,
    lng: -83.4872222222222,
    elevation_m: 3520,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Limón',
    canton: 'Limón',
    distrito: 'Valle La Estrella',
    proceso: 'Glacial y fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.81,
    valorAnadido: 0.78,
    summary: 'Geomorfositio de proceso glacial y fluvial, dentro de Parque Nacional Chirripó, en el distrito de Valle La Estrella, cantón de Limón, provincia de Limón, a 3520 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.81, valor añadido 0.78). Carácter: Natural.'
  },
  {
    id: 'chigla006',
    category: 'glaciar',
    name: 'Laguna Ditkevi',
    region: 'Telire, Talamanca, Limón',
    lat: 9.47,
    lng: -83.48,
    elevation_m: 3460,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Limón',
    canton: 'Talamanca',
    distrito: 'Telire',
    proceso: 'Glacial y fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.69,
    valorAnadido: 0.52,
    summary: 'Geomorfositio de proceso glacial y fluvial, dentro de Parque Nacional Chirripó, en el distrito de Telire, cantón de Talamanca, provincia de Limón, a 3460 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.69, valor añadido 0.52). Carácter: Natural.'
  },
  {
    id: 'chigla007',
    category: 'glaciar',
    name: 'Morrena Loma Larga',
    region: 'Chirripó, Turrialba, Cartago',
    lat: 9.50833333333333,
    lng: -83.4963888888889,
    elevation_m: 3400,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Cartago',
    canton: 'Turrialba',
    distrito: 'Chirripó',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Chirripó, cantón de Turrialba, provincia de Cartago, a 3400 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'chigla008',
    category: 'glaciar',
    name: 'Cerro Ventisqueros',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.47583333333333,
    lng: -83.5102777777778,
    elevation_m: 3812,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3812 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'chivol009',
    category: 'volcanico',
    name: 'Los Crestones',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.45138888888889,
    lng: -83.4983333333333,
    elevation_m: 3715,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.88,
    valorAnadido: 0.9,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3715 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.88, valor añadido 0.90). Carácter: Natural.'
  },
  {
    id: 'chigla010',
    category: 'glaciar',
    name: 'Sabana de los Leones',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.42055555555556,
    lng: -83.5091666666667,
    elevation_m: 3200,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glaciofluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso glaciofluvial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3200 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'chigla011',
    category: 'glaciar',
    name: 'Cerros Cuerici',
    region: 'Orosi, Paraíso, Cartago',
    lat: 9.58111111111111,
    lng: -83.6352777777778,
    elevation_m: 3345,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Cartago',
    canton: 'Paraíso',
    distrito: 'Orosi',
    proceso: 'Periglacial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.69,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso periglacial, dentro de Parque Nacional Chirripó, en el distrito de Orosi, cantón de Paraíso, provincia de Cartago, a 3345 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.69, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'chigla012',
    category: 'glaciar',
    name: 'Cerro Urán',
    region: 'Chirripó, Turrialba, Cartago',
    lat: 9.51,
    lng: -83.5347222222222,
    elevation_m: 3600,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Cartago',
    canton: 'Turrialba',
    distrito: 'Chirripó',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.5,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Chirripó, cantón de Turrialba, provincia de Cartago, a 3600 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.50, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'chigla013',
    category: 'glaciar',
    name: 'Cerro Terbi',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.45527777777778,
    lng: -83.4947222222222,
    elevation_m: 3765,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.5,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3765 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.50, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'chigla014',
    category: 'glaciar',
    name: 'Cerro Laguna',
    region: 'Valle La Estrella, Limón, Limón',
    lat: 9.50277777777778,
    lng: -83.4816666666667,
    elevation_m: 3749,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'Limón',
    canton: 'Limón',
    distrito: 'Valle La Estrella',
    proceso: 'Glacial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.56,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso glacial, dentro de Parque Nacional Chirripó, en el distrito de Valle La Estrella, cantón de Limón, provincia de Limón, a 3749 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.56, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'piagla001',
    category: 'sin-clasificar',
    name: 'Cerro Kamuk',
    region: 'Telire, Talamanca, Limón',
    lat: 9.27067,
    lng: -83.03241,
    elevation_m: 3549,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Limón',
    canton: 'Talamanca',
    distrito: 'Telire',
    proceso: null,
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.6,
    valorAnadido: 0.5,
    summary: 'Geomorfositio sin proceso geomorfológico principal registrado en el inventario, dentro de Parque Internacional La Amistad, en el distrito de Telire, cantón de Talamanca, provincia de Limón, a 3549 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.60, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'pia002',
    category: 'sin-clasificar',
    name: 'Sabanas Esperanza',
    region: 'Biolley, Buenos Aires, Puntarenas',
    lat: 9.08083333,
    lng: -83.02777778,
    elevation_m: 1800,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Buenos Aires',
    distrito: 'Biolley',
    proceso: null,
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.24,
    valorAnadido: 0.1,
    summary: 'Geomorfositio sin proceso geomorfológico principal registrado en el inventario, dentro de Parque Internacional La Amistad, en el distrito de Biolley, cantón de Buenos Aires, provincia de Puntarenas, a 1800 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.24, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pia003',
    category: 'sin-clasificar',
    name: 'Valle del Silencio',
    region: 'Biolley, Buenos Aires, Puntarenas',
    lat: 9.068333333,
    lng: -82.98055556,
    elevation_m: 2559,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Buenos Aires',
    distrito: 'Biolley',
    proceso: null,
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.35,
    valorAnadido: 0.21,
    summary: 'Geomorfositio sin proceso geomorfológico principal registrado en el inventario, dentro de Parque Internacional La Amistad, en el distrito de Biolley, cantón de Buenos Aires, provincia de Puntarenas, a 2559 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.35, valor añadido 0.21). Carácter: Natural.'
  },
  {
    id: 'pcbflu001',
    category: 'fluvial',
    name: 'Sitio Arqueológico Piedra Pintada',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.862777778,
    lng: -82.96583333,
    elevation_m: 910,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.75,
    valorAnadido: 0.8,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 910 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.75, valor añadido 0.80). Carácter: Natural.'
  },
  {
    id: 'pcbflu002',
    category: 'fluvial',
    name: 'Humedal Laguna El Campo',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.829166667,
    lng: -82.95833333,
    elevation_m: 1000,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.17,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 1000 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.17, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu003',
    category: 'fluvial',
    name: 'Humedal de San Vito',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.826708333,
    lng: -82.95083611,
    elevation_m: 990,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.16,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 990 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.16, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu004',
    category: 'fluvial',
    name: 'Humedal Laguna Zoncho',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.813,
    lng: -82.963,
    elevation_m: 1190,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.15,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 1190 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.15, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu005',
    category: 'fluvial',
    name: 'Humedal Laguna Los Gamboa',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.788611111,
    lng: -82.98472222,
    elevation_m: 1454,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.22,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 1454 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.22, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu006',
    category: 'fluvial',
    name: 'Humedal Palustrino Laguna El Paraguas',
    region: 'San Vito, Coto Brus, Puntarenas',
    lat: 8.782222222,
    lng: -82.98111111,
    elevation_m: 1400,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'San Vito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.19,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de San Vito, cantón de Coto Brus, provincia de Puntarenas, a 1400 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.19, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu007',
    category: 'fluvial',
    name: 'Catarata La Neblina',
    region: 'Sabalito, Coto Brus, Puntarenas',
    lat: 8.908888889,
    lng: -82.76055556,
    elevation_m: 1650,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Sabalito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.45,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Sabalito, cantón de Coto Brus, provincia de Puntarenas, a 1650 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.45, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'pcbflu008',
    category: 'fluvial',
    name: 'Toma de agua Acueducto Las Tablas',
    region: 'Sabalito, Coto Brus, Puntarenas',
    lat: 8.942861111,
    lng: -82.74583333,
    elevation_m: 1780,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Sabalito',
    proceso: 'Fluvial',
    caracteristica: 'Antrópica',
    clasificacion: 'Baja',
    valorCientifico: 0.15,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Sabalito, cantón de Coto Brus, provincia de Puntarenas, a 1780 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.15, valor añadido 0.50). Carácter: Antrópica.'
  },
  {
    id: 'pcbflu009',
    category: 'fluvial',
    name: 'Catarata Salto del Ángel',
    region: 'Sabalito, Coto Brus, Puntarenas',
    lat: 8.929722222,
    lng: -82.74861111,
    elevation_m: 1950,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Sabalito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.56,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Sabalito, cantón de Coto Brus, provincia de Puntarenas, a 1950 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.56, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'pcbtec010',
    category: 'tectonico',
    name: 'Cerro Pelón',
    region: 'Sabalito, Coto Brus, Puntarenas',
    lat: 8.917222222,
    lng: -82.78694444,
    elevation_m: 1450,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Sabalito',
    proceso: 'Tectónico',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.24,
    valorAnadido: 0.2,
    summary: 'Geomorfositio de proceso tectónico, en el distrito de Sabalito, cantón de Coto Brus, provincia de Puntarenas, a 1450 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.24, valor añadido 0.20). Carácter: Natural.'
  },
  {
    id: 'pcbvol011',
    category: 'volcanico',
    name: 'Cerro Quijada del Diablo',
    region: 'Sabalito, Coto Brus, Puntarenas',
    lat: 8.90654,
    lng: -82.74914,
    elevation_m: 1850,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Sabalito',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.71,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso volcánico, en el distrito de Sabalito, cantón de Coto Brus, provincia de Puntarenas, a 1850 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.71, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'pcbflu012',
    category: 'fluvial',
    name: 'Laguna Cañas Gordas',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.748888889,
    lng: -82.91944444,
    elevation_m: 1154,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.11,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 1154 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.11, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu013',
    category: 'fluvial',
    name: 'Catarata Metaponto',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.716833333,
    lng: -82.95352778,
    elevation_m: 1030,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.72,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 1030 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.72, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'pcbflu014',
    category: 'fluvial',
    name: 'Catarata Las Lajas',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.716388889,
    lng: -82.93638889,
    elevation_m: 1075,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.16,
    valorAnadido: 0.14,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 1075 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.16, valor añadido 0.14). Carácter: Natural.'
  },
  {
    id: 'pcbflu015',
    category: 'fluvial',
    name: 'Catarata Los Vargas',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.709722222,
    lng: -82.93083333,
    elevation_m: 990,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.15,
    valorAnadido: 0.14,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 990 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.15, valor añadido 0.14). Carácter: Natural.'
  },
  {
    id: 'pcbflu016',
    category: 'fluvial',
    name: 'Laguna Campo Dos y Medio',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.705555556,
    lng: -82.93333333,
    elevation_m: 1036,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.13,
    valorAnadido: 0.12,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 1036 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.13, valor añadido 0.12). Carácter: Natural.'
  },
  {
    id: 'pcbflu017',
    category: 'fluvial',
    name: 'Humedal Laguna Metaponto',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.706111111,
    lng: -82.93388889,
    elevation_m: 1020,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.14,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 1020 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.14, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbkar018',
    category: 'karstico',
    name: 'Caverna Barranquilla',
    region: 'Agua Buena, Coto Brus, Puntarenas',
    lat: 8.700277778,
    lng: -82.95944444,
    elevation_m: 900,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Agua Buena',
    proceso: 'Kárstico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.79,
    valorAnadido: 0.8,
    summary: 'Geomorfositio de proceso kárstico, en el distrito de Agua Buena, cantón de Coto Brus, provincia de Puntarenas, a 900 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.79, valor añadido 0.80). Carácter: Natural.'
  },
  {
    id: 'pcbflu019',
    category: 'fluvial',
    name: 'Localidad Fosilífera de San Gerardo',
    region: 'Limoncito, Coto Brus, Puntarenas',
    lat: 8.855444444,
    lng: -83.08108333,
    elevation_m: 700,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Limoncito',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.6,
    valorAnadido: 0.6,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Limoncito, cantón de Coto Brus, provincia de Puntarenas, a 700 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.60, valor añadido 0.60). Carácter: Natural.'
  },
  {
    id: 'pcbvol020',
    category: 'volcanico',
    name: 'Cerro Pittier',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 9.060833333,
    lng: -82.94111111,
    elevation_m: 2844,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.82,
    valorAnadido: 0.9,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Internacional La Amistad, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 2844 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.82, valor añadido 0.90). Carácter: Natural.'
  },
  {
    id: 'pcbvol021',
    category: 'volcanico',
    name: 'Cerro Gémelo',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 9.045555556,
    lng: -82.93527778,
    elevation_m: 2702,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.79,
    valorAnadido: 0.8,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Internacional La Amistad, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 2702 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.79, valor añadido 0.80). Carácter: Natural.'
  },
  {
    id: 'pcbflu022',
    category: 'fluvial',
    name: 'Catarata Cerro Pittier',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 9.026944444,
    lng: -82.95388889,
    elevation_m: 1680,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.78,
    valorAnadido: 0.75,
    summary: 'Geomorfositio de proceso fluvial, dentro de Parque Internacional La Amistad, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 1680 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.78, valor añadido 0.75). Carácter: Natural.'
  },
  {
    id: 'pcbflu023',
    category: 'fluvial',
    name: 'Catarata La Perla',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 9.024444444,
    lng: -82.97555556,
    elevation_m: 1300,
    areaProtegida: 'Parque Internacional La Amistad',
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.61,
    valorAnadido: 0.5,
    summary: 'Geomorfositio de proceso fluvial, dentro de Parque Internacional La Amistad, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 1300 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.61, valor añadido 0.50). Carácter: Natural.'
  },
  {
    id: 'pcbflu024',
    category: 'fluvial',
    name: 'Catarata La Esmeralda',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.965,
    lng: -83.0025,
    elevation_m: 620,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.43,
    valorAnadido: 0.4,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 620 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.43, valor añadido 0.40). Carácter: Natural.'
  },
  {
    id: 'pcbflu025',
    category: 'fluvial',
    name: 'Catarata Kamakiri',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.884166667,
    lng: -82.99583333,
    elevation_m: 820,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Media',
    valorCientifico: 0.44,
    valorAnadido: 0.45,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 820 msnm. Clasificación de valor geomorfológico: Media (valor científico 0.44, valor añadido 0.45). Carácter: Natural.'
  },
  {
    id: 'pcbflu026',
    category: 'fluvial',
    name: 'Aguas Termales de Aguas Calientes',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.946944444,
    lng: -82.92055556,
    elevation_m: 940,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.19,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 940 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.19, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu027',
    category: 'fluvial',
    name: 'Catarata Farallón Santa Fe',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.935555556,
    lng: -83.0075,
    elevation_m: 750,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.18,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 750 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.18, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu028',
    category: 'fluvial',
    name: 'Catarata Farallón Santa Fe #2',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.942777778,
    lng: -83.00722222,
    elevation_m: 730,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.12,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 730 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.12, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu029',
    category: 'fluvial',
    name: 'Catarata La Chobá',
    region: 'Pittier, Coto Brus, Puntarenas',
    lat: 8.9,
    lng: -82.98333333,
    elevation_m: 750,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Pittier',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.11,
    valorAnadido: 0.1,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Pittier, cantón de Coto Brus, provincia de Puntarenas, a 750 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.11, valor añadido 0.10). Carácter: Natural.'
  },
  {
    id: 'pcbflu030',
    category: 'fluvial',
    name: 'Catarata El Pedregal',
    region: 'Gutiérrez Braun, Coto Brus, Puntarenas',
    lat: 8.888055556,
    lng: -82.98277778,
    elevation_m: 750,
    areaProtegida: null,
    provincia: 'Puntarenas',
    canton: 'Coto Brus',
    distrito: 'Gutiérrez Braun',
    proceso: 'Fluvial',
    caracteristica: 'Natural',
    clasificacion: 'Baja',
    valorCientifico: 0.16,
    valorAnadido: 0.15,
    summary: 'Geomorfositio de proceso fluvial, en el distrito de Gutiérrez Braun, cantón de Coto Brus, provincia de Puntarenas, a 750 msnm. Clasificación de valor geomorfológico: Baja (valor científico 0.16, valor añadido 0.15). Carácter: Natural.'
  },
  {
    id: 'psrtec001',
    category: 'tectonico',
    name: 'Península de Santa Elena',
    region: 'Santa Elena, La Cruz, Guanacaste',
    lat: 10.87034726,
    lng: -85.72818046,
    elevation_m: null,
    areaProtegida: 'Parque Nacional Santa Rosa',
    provincia: 'Guanacaste',
    canton: 'La Cruz',
    distrito: 'Santa Elena',
    proceso: 'Tectónico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.85,
    valorAnadido: 0.9,
    summary: 'Geomorfositio de proceso tectónico, dentro de Parque Nacional Santa Rosa, en el distrito de Santa Elena, cantón de La Cruz, provincia de Guanacaste. Clasificación de valor geomorfológico: Alta (valor científico 0.85, valor añadido 0.90). Carácter: Natural.'
  },
  {
    id: 'chivol015',
    category: 'volcanico',
    name: 'Cerro Páramo',
    region: 'Rivas, Pérez Zeledón, San José',
    lat: 9.463556,
    lng: -83.510306,
    elevation_m: 3699,
    areaProtegida: 'Parque Nacional Chirripó',
    provincia: 'San José',
    canton: 'Pérez Zeledón',
    distrito: 'Rivas',
    proceso: 'Volcánico',
    caracteristica: 'Natural',
    clasificacion: 'Alta',
    valorCientifico: 0.84,
    valorAnadido: 0.82,
    summary: 'Geomorfositio de proceso volcánico, dentro de Parque Nacional Chirripó, en el distrito de Rivas, cantón de Pérez Zeledón, provincia de San José, a 3699 msnm. Clasificación de valor geomorfológico: Alta (valor científico 0.84, valor añadido 0.82). Carácter: Natural.'
  }
];
